# Generated by Django 4.2.4 on 2023-09-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_song_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='default_audio.mp3', upload_to='songs/'),
        ),
    ]
